# Generated by Django 3.2.12 on 2022-02-24 20:41

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('trabajo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Trabajo')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
